marinebox/tab-killer

- src/background.js
- src/popup.html
- src/popup.js
> white list機能を追加(UIのみ)

- src/popup.html
- src/popup.js
ホワイトリスト機能のバックエンド面の実装をした。
- ホワイトリストの初期化、追加、削除をできるようにした。
- 通常の重複タブ削除を行う際、ホワイトリストと照合を行うようにした。
> whitelist機能の追加(storage)

- src/background.js
- src/manifest.json
- src/popup.html
- src/popup.js
> ホワイトリスト機能の実装

- src/popup.html
- src/popup.js
- tag切り替え( Console / White List / **History** )
- popup表示時にstorageの内容を反映
> 履歴機能の実装(UI部分)

- src/popup.js
> tooltipがでる条件を修正

- .eslintrc.js
- package.json
- src/js/background.js
- src/js/history.js
- src/js/screenSwitch.js
- src/js/whitelist.js
- yarn.lock
- eslintのルールを追加
- 怒られたところを修正
- https://qiita.com/mysticatea/items/f523dab04a25f617c87d
- https://github.com/dustinspecker/awesome-eslint
`eslint:recommended`だけでもいいんだけど、これだけだと少し緩い
自分でルールをカスタマイズするのもメンテナンス上も大変なので、有名なものを借りることにした
なんとなくgoogleのものを採用->[eslint-config-google](https://github.com/google/eslint-config-google)
```a.sh
git pull
npm install or yarn install
```
> ESLintをもう少しちゃんと設定した

- .gitignore
- src/js/popup.js
fix #57 
ホワイトリストが未定義のとき動作が停止するので、例外処理を記述した。
> ホワイトリスト未定義時に重複タブ削除が動作しない問題の修正

- src/js/whitelist.js
- src/popup.html
> ホワイトリストオールクリア機能

- README.md
> READMEを書いた

- src/js/popup.js
resolve #49 
マウスオーバー時に何を消すのか表示するようにした
Historyと同じようなtooltipが使いたかったけど改行ができなかったので標準のやつで代用した
https://user-images.githubusercontent.com/60165927/144006568-617b95b2-518c-4b24-ab0d-b8be63368412.mov
> 重複の中身をわかるようにした

- src/js/whitelist.js
- src/popup.html
resolve #35 
1. 使われていない`export`を削除した
2. 雰囲気でbulmaいじってボタン作った
3. JS書いた
https://user-images.githubusercontent.com/60165927/144006149-55cf9feb-49eb-4ef2-a5d3-db16226ec7a6.mov
> ホワイトリストを追加しやすくした

- src/js/whitelist.js
resolve #64 
memo: コールバック周りを整理したい
> ホワイトリスト追加時、重複を防ぐ機能

- src/js/whitelist.js
resolve #66
https://user-images.githubusercontent.com/56141035/144360169-d966745f-7f19-42c2-b311-3df0fc33c31f.mov
> ホワイトリスト全削除前に確認

- src/js/language.js
> ホワイトリストボタン英語対応

- src/js/history.js
- src/js/language.js
- src/js/popup.js
- src/js/utils.js
- src/js/whitelist.js
参考:
- https://www.cyamax.com/entry/2021/06/01/070000
- https://qiita.com/kururua/items/06c9eab514221da4111b
`chrome.tabs.query`は大変なので別issueかな
> ストレージAPI周りをPromiseで共通化

- src/js/language.js
- src/popup.html
> デフォルト言語をブラウザ依存にした

- src/js/popup.js
> isOverWindowsをstorageから引き出す

- src/js/background.js
- src/manifest.json
> background.jsもimportできるようにした

- src/js/history.js
resolve: #85
描画時に少し時間がかかるのが難点かもしれない
参考：https://taneppa.net/favicon_api_bookmark/
> historyにfaviconを追加

- src/js/history.js
> 最後の一つ消せるようにした

- src/_locales/en/messages.json
- src/_locales/ja/messages.json
- src/manifest.json
> 拡張機能本体の国際化

- src/js/domain.js
> ドメイン削除ボタンにfaviconを追加

- src/js/domain.js
- src/js/popup.js
resolve #93 
https://user-images.githubusercontent.com/60165927/144994576-43cc9a19-7424-45f4-b289-de523807b9bc.mov
> ドメイン削除も対象ウィンドウを選べるようにした

- src/js/background.js
- src/manifest.json
resolve #97 
とりあえずimportしないようにして解消
> バッジが更新されてないバグの解消

- src/js/history.js
- src/js/language.js
- src/js/popup.js
- src/js/utils.js
- src/js/whitelist.js
> setStorage共通化

- src/js/history.js
resolve #101 
https://user-images.githubusercontent.com/56141035/145441192-1f1534b1-3992-4bf0-8133-78a81294e42f.mov
とりあえず間に合わせでindexで削除するように変更
今後idとか付けて一意に判断したい感じはある
> history削除バグ修正

- src/js/domain.js
- src/js/history.js
> favicon取得APIを変更

- src/popup.html
@marinebox 
どうだろうか
参考
https://fontawesome.com/v5.15/icons
> ツールバーにアイコンを追加してみた

- src/icon/phosphor.css
- src/js/popup.js
- src/js/utils.js
- src/popup.html
https://user-images.githubusercontent.com/56141035/146984429-b02cf0bd-e9c9-4c98-bff7-699941b43cce.mov
使ったアイコン
https://phosphoricons.com/
> 全ウィンドウ対象否をアイコンでわかりやすく

- src/_locales/en/messages.json
- src/_locales/ja/messages.json
- src/js/background.js
- src/manifest.json
partial #113 
(ブランチ名に反するが)ショートカット機能のみを実装した
> ショートカット機能の実装

- package.json
- src/popup.html
- yarn.lock
> タイトルの横にメインアイコンを追加してみた

- src/js/popup.js
- src/popup.html
> phosphorの読み込みが遅いのを解決する

- src/js/domain.js
- src/js/language.js
- src/js/popup.js
- src/js/utils.js
> ホワイトリストにあるものはドメイン削除、ワード削除でも削除されなくする

- src/js/background.js
for文で数える方式からSet作って要素数の差を取る方法に変更
ほんの少し軽くなるでしょ(適当)
> バッジ表示用の重複タブカウントアルゴリズムの変更

- src/js/popup.js
> 重複タブ削除時の計算量削減

- src/js/domain.js
- src/js/history.js
- src/js/language.js
- src/js/popup.js
- src/js/utils.js
- src/js/whitelist.js
> storage周りの関数の整理
